services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        ENVIRONMENT: production
    container_name: php-prod-stack
    ports:
      - "80:80"
    volumes:
      # PRODUCTION: Only logs mapping, no live code editing
      - ./logs:/var/log/app:rw
    environment:
      - APP_ENV=production     # ✅ Aplikacja wie, że to prod
      - APP_DEBUG=false        # ✅ Bez debug info
      - LOG_LEVEL=error        # ✅ Tylko błędy
      - XDEBUG_MODE=off        # ✅ Wyłączony Xdebug
    networks:
      - prod-network
    restart: always
    # Production-specific settings
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

networks:
  prod-network:
    driver: bridge
