services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        ENVIRONMENT: development
    container_name: php-dev-stack
    ports:
      - "8080:80"
      - "9003:9003"  # Xdebug port
    volumes:
      # DEVELOPMENT ONLY: Live code editing
      - ./app:/var/www/html
      # Log files mapping for easy access
      - ./logs:/var/log/app
    environment:
      - APP_ENV=development
      - PHP_ENV=development
      - XDEBUG_MODE=debug
      - XDEBUG_CONFIG=client_host=host.docker.internal
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - dev-network
    restart: unless-stopped

networks:
  dev-network:
    driver: bridge
