services:
  web:
    build:
      context: ./docker
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "9003:9003"
    volumes:
      - .:/var/www/html
      - ./logs:/var/log/app
    environment:
      - PHP_IDE_CONFIG=serverName=Docker
      - TZ=Europe/Warsaw
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
