services:
  web:
    build:
      context: ./docker
      dockerfile: Dockerfile
      args:
        ENVIRONMENT: production
    environment:
      - APP_ENV=production
      - PHP_ENV=prod
    ports:
      - "80:80"
      # Brak portu 9003 w prod
    volumes:
      - ./app:/var/www/html
      - ./logs:/var/log/app
